const palettes=[['#f3f0df','#111111','#ff2d95','#55f274','#1e52bd','#f3e51f','#9ddcf4'],['#0a170d','#b8ff21','#00b7ff','#ff337f','#f6e926','#f1f0e8','#1b38b6'],['#f2ebcf','#ff3da2','#1c1b1a','#72d543','#8576df','#f49977','#1963bd'],['#ecebea','#111111','#ff4b30','#52f27a','#efacd0','#194ba0','#ffdf1b']];
let custom=[...palettes[0]],settings={seed:37720174,pixel:15,chaos:58,density:64,stripes:40,noise:34,color:0,sourceMix:82},source=null,ratio='portrait';
const canvas=document.querySelector('#art'),frame=document.querySelector('#frame'),seed=document.querySelector('#seed');
const sliderDefs=[['pixel','BLOCK SIZE',5,36],['chaos','DISPLACEMENT',0,100],['density','COLLAGE DENSITY',0,100],['stripes','SCAN BARS',0,100],['noise','XEROX NOISE',0,100],['sourceMix','SOURCE PRESENCE',0,100]];
function mulberry32(a){return()=>{a|=0;a=a+0x6d2b79f5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function noisePattern(ctx,n){const c=document.createElement('canvas');c.width=c.height=72;const x=c.getContext('2d');x.fillStyle='#f3f0df';x.fillRect(0,0,72,72);x.fillStyle='#101010';for(let i=0;i<n*3;i++)x.fillRect(Math.random()*72,Math.random()*72,1.2,1.2);return ctx.createPattern(c,'repeat')}
function draw(){const dims=ratio==='portrait'?[900,1125]:ratio==='square'?[1000,1000]:[1200,800];canvas.width=dims[0];canvas.height=dims[1];const ctx=canvas.getContext('2d',{alpha:false}),w=canvas.width,h=canvas.height,rnd=mulberry32(settings.seed),p=[...palettes,custom][settings.color]||palettes[0],px=Math.max(5,settings.pixel);ctx.imageSmoothingEnabled=false;ctx.fillStyle=p[0];ctx.fillRect(0,0,w,h);
if(source){const t=document.createElement('canvas'),tw=Math.max(20,Math.floor(w/px)),th=Math.max(20,Math.floor(h/px));t.width=tw;t.height=th;const tc=t.getContext('2d'),sr=source.width/source.height,tr=w/h;let sx=0,sy=0,sw=source.width,sh=source.height;if(sr>tr){sw=source.height*tr;sx=(source.width-sw)/2}else{sh=source.width/tr;sy=(source.height-sh)/2}tc.drawImage(source,sx,sy,sw,sh,0,0,tw,th);const d=tc.getImageData(0,0,tw,th);for(let i=0;i<d.data.length;i+=4){const lum=(d.data[i]*.299+d.data[i+1]*.587+d.data[i+2]*.114)/255,idx=Math.min(p.length-1,Math.floor(lum*p.length)),hex=p[(idx+settings.color)%p.length];d.data[i]=parseInt(hex.slice(1,3),16);d.data[i+1]=parseInt(hex.slice(3,5),16);d.data[i+2]=parseInt(hex.slice(5,7),16)}tc.putImageData(d,0,0);ctx.globalAlpha=settings.sourceMix/100;ctx.drawImage(t,0,0,tw,th,0,0,w,h);ctx.globalAlpha=1;for(let i=0;i<Math.floor(settings.chaos/5);i++){const y=Math.floor(rnd()*th)*px,hh=(1+Math.floor(rnd()*7))*px,shift=(rnd()-.5)*settings.chaos*7;ctx.drawImage(canvas,0,y,w,hh,shift,y,w,hh)}}
for(let i=0;i<Math.floor(settings.density*4.75);i++){const x=Math.floor(rnd()*w/px)*px,y=Math.floor(rnd()*h/px)*px,ww=px*(1+Math.floor(rnd()*(2+settings.chaos/12))),hh=px*(1+Math.floor(rnd()*(2+settings.chaos/16)));ctx.fillStyle=rnd()<settings.noise/280?(noisePattern(ctx,settings.noise)||p[1]):p[Math.floor(rnd()*p.length)];ctx.globalAlpha=source ? .36+rnd()*.44 : .8+rnd()*.2;ctx.fillRect(x,y,ww,hh)}ctx.globalAlpha=1;
for(let g=0;g<Math.floor(settings.stripes/9);g++){const x=Math.floor(rnd()*w/px)*px,y=Math.floor(rnd()*h/px)*px,sw=px*(2+Math.floor(rnd()*5)),sh=px*(5+Math.floor(rnd()*14));ctx.fillStyle=p[1];ctx.fillRect(x,y,sw,sh);ctx.fillStyle=p[0];for(let yy=y+px/2;yy<y+sh;yy+=px)ctx.fillRect(x,yy,sw,Math.max(2,px/4))}ctx.lineWidth=px;ctx.strokeStyle=p[2];ctx.lineJoin='miter';for(let row=0;row<3;row++){ctx.beginPath();let y=h*(.17+row*.11);ctx.moveTo(0,y);for(let x=0;x<=w;x+=px*3){y+=(rnd()>.52?1:-1)*px;ctx.lineTo(x,y);ctx.lineTo(x+px*2,y)}ctx.stroke()}if(settings.noise>5){ctx.globalAlpha=settings.noise/330;ctx.fillStyle=noisePattern(ctx,settings.noise)||'#000';ctx.fillRect(0,0,w,h);ctx.globalAlpha=1}}
function renderControls(){seed.value=settings.seed;const s=document.querySelector('#sliders');s.innerHTML='';sliderDefs.forEach(([key,label,min,max])=>{const wrap=document.createElement('label');wrap.className='slider-row';wrap.innerHTML=`<div><span>${label}</span><b>${settings[key]}</b></div><input type="range" min="${min}" max="${max}" value="${settings[key]}">`;wrap.querySelector('input').addEventListener('input',e=>{settings[key]=Number(e.target.value);wrap.querySelector('b').textContent=settings[key];draw()});s.append(wrap)});document.querySelectorAll('.palette-grid button').forEach((b,i)=>b.classList.toggle('active',i===settings.color));document.querySelector('#customPalette').classList.toggle('active',settings.color===palettes.length)}
palettes.forEach((p,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',`Palette ${i+1}`);p.slice(1,5).forEach(c=>{const sw=document.createElement('i');sw.style.background=c;b.append(sw)});b.onclick=()=>{settings.color=i;renderControls();draw()};document.querySelector('#palettes').append(b)});custom.forEach((c,i)=>{const input=document.createElement('input');input.type='color';input.value=c;input.setAttribute('aria-label',`Custom color ${i+1}`);input.oninput=e=>{custom[i]=e.target.value;settings.color=palettes.length;renderControls();draw()};document.querySelector('#colors').append(input)});
seed.addEventListener('change',e=>{settings.seed=Number(e.target.value)||1;draw()});document.querySelector('#useCustom').onclick=()=>{settings.color=palettes.length;renderControls();draw()};document.querySelector('#randomize').onclick=()=>{settings={seed:Math.floor(Math.random()*99999999),pixel:7+Math.floor(Math.random()*25),chaos:25+Math.floor(Math.random()*76),density:Math.floor(Math.random()*101),stripes:Math.floor(Math.random()*101),noise:10+Math.floor(Math.random()*81),color:Math.floor(Math.random()*(palettes.length+1)),sourceMix:60+Math.floor(Math.random()*41)};renderControls();draw()};
document.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>{ratio=b.dataset.ratio;frame.className=`canvas-frame ${ratio}`;document.querySelectorAll('[data-ratio]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#formatLabel').textContent=`${ratio==='portrait'?'4:5':ratio==='square'?'1:1':'3:2'} / RGB`;draw()});
const file=document.querySelector('#file'),drop=document.querySelector('#dropzone');function load(f){if(!f?.type.startsWith('image/'))return;const img=new Image;img.onload=()=>{source=img;document.querySelector('#fileName').textContent=f.name.toUpperCase();document.querySelector('#sourceLight').classList.add('online');document.querySelector('#remove').hidden=false;draw()};img.src=URL.createObjectURL(f)}drop.onclick=()=>file.click();file.onchange=e=>load(e.target.files[0]);drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging')};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragging');load(e.dataTransfer.files[0])};document.querySelector('#remove').onclick=()=>{source=null;document.querySelector('#fileName').textContent='NO SOURCE / GENERATIVE MODE';document.querySelector('#sourceLight').classList.remove('online');document.querySelector('#remove').hidden=true;draw()};document.querySelector('#export').onclick=()=>{const a=document.createElement('a');a.download=`signal-${settings.seed}.png`;a.href=canvas.toDataURL('image/png');a.click()};renderControls();draw();
